name: Deploy
author: Arsanukaev Adam
description: Test, deploy and release solution to Heroku

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy solution
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Deploy on Heroku
        run: make webapi.heroku HEROKU_API_KEY=${{ secrets.HEROKU_API_KEY }}