name: Pull Request
author: Adam Arsanukaev
description: Build and run tests on pull request

on: [pull_request]

jobs:
  test:
    name: Test solution
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Build and test
        run: make webapi