name: On pull request

on:
  pull_request:
    branches-ignore:
      - *doc

jobs:
  build:
    name: Build and test solution
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Build and test solution
        run: make webapi